export const WEEK_LABEL = "Semaine du 13 avril 2026";

export const OPPORTUNITIES = [
  {
    "id": 1,
    "name": "IA de génération de devis pour artisans BTP",
    "category": "btp",
    "score": 94,
    "scores": {
      "demande": 23,
      "croissance": 24,
      "concurrence": 19,
      "monetisation": 14,
      "faisabilite": 14
    },
    "trend": "+310%",
    "market": "€3.2B",
    "type": "SaaS",
    "mentions": 1840,
    "sources": "Reddit, Forums Pro, Google Trends",
    "problem": "Les artisans et petites entreprises du BTP passent en moyenne 4 à 6 heures par semaine à rédiger des devis manuellement. Les erreurs de chiffrage sont fréquentes, les relances inexistantes, et beaucoup de devis sont envoyés trop tard — ce qui fait perdre des chantiers. Aucun outil actuel ne combine IA + catalogue matériaux + suivi client de manière simple et adaptée aux TPE du bâtiment.",
    "solution": "Un SaaS qui génère des devis en quelques minutes grâce à l'IA. L'artisan décrit le chantier, l'outil propose un devis structuré avec les bons matériaux et prix à jour. Fonctionnalités clés : catalogue matériaux intégré avec prix fournisseurs, génération automatique par description vocale ou texte, signature électronique, relance automatique des devis en attente. Cible : artisans solo et PME du bâtiment (plombiers, électriciens, maçons). Pricing suggéré : 39€/mois solo, 99€/mois équipe.",
    "competitors": "Peu de concurrence IA directe. Quelques outils classiques (Obat, Batappli) mais sans intelligence artificielle.",
    "weekTrend": "stable"
  },
  {
    "id": 2,
    "name": "Outils IA pour études notariales",
    "category": "tech",
    "score": 91,
    "scores": {
      "demande": 21,
      "croissance": 23,
      "concurrence": 20,
      "monetisation": 14,
      "faisabilite": 13
    },
    "trend": "+180%",
    "market": "€2.1B",
    "type": "SaaS",
    "mentions": 920,
    "sources": "Twitter/X, Forums juridiques, Google Trends",
    "problem": "Les notaires et clercs de notaire passent un temps considérable sur la rédaction d'actes répétitifs, la recherche de jurisprudence et la vérification de conformité. La profession est en retard sur la digitalisation et les outils existants sont vieillissants et peu intuitifs. La demande pour des outils modernes augmente avec l'arrivée d'une nouvelle génération de notaires.",
    "solution": "Un assistant IA spécialisé pour le notariat : rédaction assistée d'actes notariés avec templates intelligents, recherche de jurisprudence par question en langage naturel, vérification automatique de conformité, gestion de dossier client intégrée. Cible : études notariales françaises (environ 6 500 offices). Pricing suggéré : 199€/mois par étude.",
    "competitors": "Marché quasi vierge en IA. Outils classiques (Genapi, Fiducial) sans couche intelligente.",
    "weekTrend": "stable"
  },
  {
    "id": 3,
    "name": "Plateforme IA pour restaurateurs",
    "category": "sante",
    "score": 89,
    "scores": {
      "demande": 22,
      "croissance": 24,
      "concurrence": 18,
      "monetisation": 13,
      "faisabilite": 12
    },
    "trend": "+230%",
    "market": "€1.8B",
    "type": "SaaS / App",
    "mentions": 1350,
    "sources": "Reddit, Twitter/X, Facebook Groups",
    "problem": "Les restaurateurs indépendants jonglent entre gestion des stocks, création de menus, commandes fournisseurs et rentabilité des plats — tout ça souvent sur papier ou Excel. Le gaspillage alimentaire est un problème majeur (10-15% de perte en moyenne). Il n'existe pas d'outil simple et abordable qui combine ces fonctions avec de l'intelligence prédictive.",
    "solution": "Une app qui utilise l'IA pour optimiser toute la chaîne : menus générés selon la saison et les marges, gestion prédictive des stocks pour réduire le gaspillage, commandes fournisseurs automatisées, dashboard de rentabilité par plat en temps réel. Cible : restaurateurs indépendants et petites chaînes. Pricing suggéré : 69€/mois.",
    "competitors": "Quelques outils de gestion (Zenchef, Lightspeed) mais aucun avec IA prédictive sur les stocks et menus.",
    "weekTrend": "stable"
  },
  {
    "id": 4,
    "name": "CRM intelligent pour freelances",
    "category": "tech",
    "score": 87,
    "scores": {
      "demande": 22,
      "croissance": 20,
      "concurrence": 17,
      "monetisation": 14,
      "faisabilite": 14
    },
    "trend": "+140%",
    "market": "€960M",
    "type": "SaaS",
    "mentions": 780,
    "sources": "Reddit, Indie Hackers, Twitter/X",
    "problem": "Les freelances utilisent un patchwork d'outils (Notion, Google Sheets, Excel) pour gérer leurs clients, projets et facturation. Il n'existe pas de CRM pensé pour le workflow freelance : prospection → devis → projet → facture → relance. Les CRM classiques (HubSpot, Salesforce) sont surdimensionnés et trop chers pour un indépendant.",
    "solution": "Un CRM minimaliste pensé freelance : pipeline visuel du prospect au paiement, génération de devis et factures intégrée, relances automatiques, dashboard revenus et prévisions, intégration bancaire pour le suivi des paiements. Cible : freelances tech, créatifs, consultants. Pricing suggéré : 19€/mois.",
    "competitors": "Concurrence modérée (Bonsai, HoneyBook) mais peu d'acteurs en français et adaptés au marché européen.",
    "weekTrend": "stable"
  },
  {
    "id": 5,
    "name": "Assistant IA pour agents immobiliers",
    "category": "immobilier",
    "score": 86,
    "scores": {
      "demande": 23,
      "croissance": 22,
      "concurrence": 16,
      "monetisation": 13,
      "faisabilite": 12
    },
    "trend": "+280%",
    "market": "€4.1B",
    "type": "SaaS",
    "mentions": 1100,
    "sources": "Google Trends, Twitter/X, Forums immo",
    "problem": "Les agents immobiliers passent 60% de leur temps sur des tâches administratives : rédaction d'annonces, réponses aux demandes, organisation des visites, suivi acquéreurs. La plupart des outils du secteur sont des CRM génériques qui ne comprennent pas les spécificités métier. La génération de leads qualifiés reste le problème numéro un.",
    "solution": "Un assistant IA métier : rédaction automatique d'annonces optimisées SEO, chatbot qualificateur de leads 24/7, matching intelligent acheteur/bien, automatisation du suivi acquéreur, estimation de prix par IA. Cible : agents indépendants et petites agences. Pricing suggéré : 89€/mois.",
    "competitors": "Quelques acteurs (Yanport, Apimo) mais sans vraie couche IA générative.",
    "weekTrend": "up"
  },
  {
    "id": 6,
    "name": "Plateforme d'emailing IA pour PME",
    "category": "marketing",
    "score": 85,
    "scores": {
      "demande": 21,
      "croissance": 19,
      "concurrence": 16,
      "monetisation": 15,
      "faisabilite": 14
    },
    "trend": "+120%",
    "market": "€2.8B",
    "type": "SaaS",
    "mentions": 680,
    "sources": "Reddit, Product Hunt, Google Trends",
    "problem": "Les PME et solopreneurs savent que l'email marketing fonctionne mais n'ont ni le temps ni les compétences pour rédiger des séquences efficaces. Les outils existants (Mailchimp, Brevo) offrent l'infrastructure mais pas la stratégie. Le taux d'ouverture moyen est de 21% et la plupart des séquences sont mal construites.",
    "solution": "Un outil qui combine envoi d'emails ET rédaction IA : l'utilisateur décrit son objectif, l'IA génère la séquence complète (objets, corps, timing, CTA), A/B testing automatique des objets, optimisation continue basée sur les résultats, templates par industrie. Cible : PME, solopreneurs, freelances. Pricing suggéré : 29€/mois.",
    "competitors": "Marché saturé en email marketing mais quasi vide en 'email strategy AI'. Opportunité de niche.",
    "weekTrend": "stable"
  },
  {
    "id": 7,
    "name": "Logiciel suivi de chantier simplifié",
    "category": "btp",
    "score": 83,
    "scores": {
      "demande": 20,
      "croissance": 21,
      "concurrence": 17,
      "monetisation": 13,
      "faisabilite": 12
    },
    "trend": "+95%",
    "market": "€1.5B",
    "type": "SaaS / App",
    "mentions": 560,
    "sources": "Forums BTP, Reddit, Google Trends",
    "problem": "Le suivi de chantier dans les petites structures se fait encore sur papier, WhatsApp et photos non organisées. Les chefs de chantier perdent du temps à documenter l'avancement, les malfaçons et la communication avec les clients. Les outils existants (Bulldozair, Finalcad) sont pensés pour les grands groupes et trop complexes pour les artisans.",
    "solution": "Une app mobile-first ultra simple : prise de photo géolocalisée et datée automatiquement, rapport d'avancement généré par IA à partir des photos, partage client en un clic, suivi des réserves et malfaçons, planning chantier visuel. Cible : artisans et petites entreprises BTP. Pricing suggéré : 29€/mois.",
    "competitors": "Concurrence orientée grands groupes. Très peu d'offre pour les TPE/PME.",
    "weekTrend": "stable"
  },
  {
    "id": 8,
    "name": "Téléconsultation IA spécialisée dermatologie",
    "category": "sante",
    "score": 81,
    "scores": {
      "demande": 20,
      "croissance": 20,
      "concurrence": 15,
      "monetisation": 14,
      "faisabilite": 12
    },
    "trend": "+160%",
    "market": "€3.6B",
    "type": "SaaS / App",
    "mentions": 490,
    "sources": "Reddit, PubMed, Twitter/X",
    "problem": "Les délais pour voir un dermatologue en France dépassent souvent 6 mois. Les patients cherchent des réponses en ligne sur des forums peu fiables. Les médecins généralistes manquent d'outils pour le pré-diagnostic dermatologique. Le marché de la télédermatologie explose mais les solutions actuelles manquent de spécialisation.",
    "solution": "Plateforme de pré-diagnostic dermatologique par IA : le patient envoie une photo, l'IA analyse et oriente (urgence, RDV dermato, conseil), connexion avec un réseau de dermatologues pour téléconsultation rapide, suivi de l'évolution des lésions dans le temps. Cible : patients, médecins généralistes, dermatologues. Pricing suggéré : B2B — 149€/mois par cabinet.",
    "competitors": "Quelques acteurs (Skin Analytics, DermoSafe) mais marché francophone quasi vierge.",
    "weekTrend": "stable"
  },
  {
    "id": 9,
    "name": "Estimateur immobilier IA pour particuliers",
    "category": "immobilier",
    "score": 79,
    "scores": {
      "demande": 21,
      "croissance": 18,
      "concurrence": 14,
      "monetisation": 13,
      "faisabilite": 13
    },
    "trend": "+105%",
    "market": "€1.2B",
    "type": "SaaS / App",
    "mentions": 720,
    "sources": "Google Trends, Reddit, Forums immo",
    "problem": "Les particuliers qui veulent vendre ou acheter un bien n'ont aucun moyen fiable d'estimer un prix juste. Les estimations en ligne (MeilleursAgents, SeLoger) sont trop génériques. Les vrais comparatifs de ventes récentes ne sont pas accessibles facilement. Résultat : des biens surévalués qui stagnent ou sous-évalués qui font perdre de l'argent.",
    "solution": "Un outil d'estimation ultra-précis basé sur les données DVF (Demandes de Valeurs Foncières), enrichi par IA : comparaison avec les ventes réelles du quartier, facteurs de correction (étage, vue, état, DPE), évolution prévisionnelle du prix, rapport PDF téléchargeable. Cible : particuliers vendeurs, investisseurs. Monétisation : gratuit → rapport premium payant (9€) ou lead gen vers agents partenaires.",
    "competitors": "MeilleursAgents domine mais l'approche IA + données DVF précises reste une niche.",
    "weekTrend": "stable"
  },
  {
    "id": 10,
    "name": "Automatisation cold outreach pour agences",
    "category": "marketing",
    "score": 77,
    "scores": {
      "demande": 19,
      "croissance": 18,
      "concurrence": 14,
      "monetisation": 14,
      "faisabilite": 12
    },
    "trend": "+90%",
    "market": "€840M",
    "type": "SaaS",
    "mentions": 540,
    "sources": "Reddit, Indie Hackers, Twitter/X",
    "problem": "Les agences marketing et communication passent un temps fou à prospecter : recherche de leads, rédaction de messages personnalisés, suivi des relances. Les outils de cold email existants (Lemlist, Instantly) gèrent l'envoi mais pas la stratégie ni la personnalisation profonde. Les taux de réponse chutent parce que les messages sont génériques.",
    "solution": "Un outil de prospection IA pour agences : scraping intelligent de prospects qualifiés, rédaction hyper-personnalisée par IA (analyse du site web du prospect, de son LinkedIn, de ses problématiques), séquences multi-canal (email + LinkedIn), dashboard de performance et optimisation auto. Cible : agences marketing, agences web, consultants. Pricing suggéré : 79€/mois.",
    "competitors": "Lemlist, Instantly, Apollo dominent l'envoi. L'angle 'stratégie + personnalisation IA' reste sous-exploité.",
    "weekTrend": "stable"
  },
  {
    "id": 11,
    "name": "Plateforme de gestion locative IA",
    "category": "immobilier",
    "score": 75,
    "scores": {
      "demande": 19,
      "croissance": 17,
      "concurrence": 14,
      "monetisation": 13,
      "faisabilite": 12
    },
    "trend": "+85%",
    "market": "€2.3B",
    "type": "SaaS",
    "mentions": 410,
    "sources": "Reddit, Forums immobilier",
    "problem": "Les propriétaires bailleurs qui gèrent 2 à 20 biens en direct n'ont pas d'outil adapté. Soit ils paient une agence (7-10% des loyers), soit ils gèrent tout manuellement. Les quittances, les relances de loyer, les déclarations fiscales, la communication avec les locataires — tout est chronophage.",
    "solution": "Un outil tout-en-un pour propriétaires bailleurs : génération automatique de quittances et relances, suivi des paiements avec alerte retard, aide à la déclaration fiscale (revenus fonciers), communication locataire centralisée, gestion des travaux et incidents. Cible : propriétaires de 2 à 20 biens. Pricing suggéré : 12€/mois par bien.",
    "competitors": "Quelques acteurs (Rentila, Ublo) mais UX datée et pas d'IA.",
    "weekTrend": "stable"
  },
  {
    "id": 12,
    "name": "Chatbot IA santé mentale entreprise",
    "category": "sante",
    "score": 73,
    "scores": {
      "demande": 18,
      "croissance": 19,
      "concurrence": 13,
      "monetisation": 12,
      "faisabilite": 11
    },
    "trend": "+145%",
    "market": "€1.9B",
    "type": "SaaS B2B",
    "mentions": 380,
    "sources": "LinkedIn, Reddit, Twitter/X",
    "problem": "La santé mentale au travail est un sujet en explosion. Les entreprises sont obligées par la loi de prévenir les risques psychosociaux mais n'ont pas d'outils pratiques. Les solutions actuelles (EAP, numéros verts) ont des taux d'utilisation inférieurs à 5% car perçues comme stigmatisantes.",
    "solution": "Un chatbot IA anonyme et confidentiel accessible à tous les salariés : check-in quotidien du bien-être, détection précoce des signaux de détresse, orientation vers les ressources adaptées, dashboard anonymisé pour les RH (tendances, pas de données individuelles). Cible : DRH, entreprises de 50 à 5000 salariés. Pricing suggéré : 3€/salarié/mois.",
    "competitors": "Moka.care, Teale existent mais le marché reste très fragmenté et en forte croissance.",
    "weekTrend": "up"
  },
  {
    "id": 13,
    "name": "Générateur de contrats freelance par IA",
    "category": "tech",
    "score": 82,
    "scores": {
      "demande": 20,
      "croissance": 19,
      "concurrence": 17,
      "monetisation": 13,
      "faisabilite": 13
    },
    "trend": "+130%",
    "market": "€680M",
    "type": "SaaS",
    "mentions": 620,
    "sources": "Reddit, Indie Hackers, Twitter/X",
    "problem": "Les freelances rédigent leurs contrats avec des templates Word trouvés en ligne, souvent juridiquement fragiles. Chaque nouveau client nécessite une adaptation manuelle. Les avocats coûtent cher pour des contrats récurrents et similaires.",
    "solution": "Un générateur de contrats IA adapté aux freelances : questionnaire simple, génération d'un contrat conforme au droit français, clauses personnalisables, signature électronique intégrée, bibliothèque de modèles par métier (dev, design, consulting). Cible : freelances et micro-entrepreneurs. Pricing suggéré : 15€/mois.",
    "competitors": "Captain Contrat existe mais vise les PME avec des prix élevés. Peu d'offre IA spécifique freelance.",
    "weekTrend": "stable"
  },
  {
    "id": 14,
    "name": "Dashboard analytics pour micro-SaaS",
    "category": "tech",
    "score": 74,
    "scores": {
      "demande": 18,
      "croissance": 17,
      "concurrence": 15,
      "monetisation": 12,
      "faisabilite": 12
    },
    "trend": "+85%",
    "market": "€420M",
    "type": "SaaS",
    "mentions": 340,
    "sources": "Indie Hackers, Twitter/X, Product Hunt",
    "problem": "Les créateurs de micro-SaaS jonglent entre Stripe, Google Analytics, Crisp et 10 autres outils pour comprendre la santé de leur produit. Aucun dashboard ne centralise MRR, churn, acquisition, support et usage en un seul endroit pour les petits produits.",
    "solution": "Un dashboard tout-en-un pour indie makers : connexion Stripe pour le MRR et churn, intégration analytics pour le trafic, métriques d'usage produit, alertes sur les indicateurs clés, rapport hebdomadaire automatique. Cible : indie hackers et créateurs de micro-SaaS. Pricing suggéré : 19€/mois.",
    "competitors": "Baremetrics et ChartMogul existent mais sont chers et surdimensionnés pour les micro-SaaS.",
    "weekTrend": "stable"
  },
  {
    "id": 15,
    "name": "Outil de pricing dynamique pour SaaS",
    "category": "tech",
    "score": 68,
    "scores": {
      "demande": 16,
      "croissance": 16,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 11
    },
    "trend": "+72%",
    "market": "€340M",
    "type": "SaaS",
    "mentions": 280,
    "sources": "Twitter/X, Indie Hackers",
    "problem": "La plupart des SaaS fixent leurs prix au feeling et ne les changent jamais. Ils perdent du revenu sur des clients prêts à payer plus, ou ratent des conversions à cause de prix trop élevés. L'A/B testing de prix est complexe à mettre en place.",
    "solution": "Un outil qui analyse le comportement utilisateur et la willingness-to-pay pour suggérer le pricing optimal. A/B test de pages pricing intégré, segmentation automatique, simulation de revenus. Cible : fondateurs SaaS early-stage. Pricing suggéré : 49€/mois.",
    "competitors": "ProfitWell (Paddle) offre certaines fonctions mais est orienté grands comptes.",
    "weekTrend": "stable"
  },
  {
    "id": 16,
    "name": "Plateforme de feedback produit IA",
    "category": "tech",
    "score": 71,
    "scores": {
      "demande": 17,
      "croissance": 18,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 11
    },
    "trend": "+95%",
    "market": "€510M",
    "type": "SaaS",
    "mentions": 390,
    "sources": "Product Hunt, Reddit, Twitter/X",
    "problem": "Les fondateurs reçoivent du feedback partout : emails, Intercom, tweets, avis app stores, appels clients. Tout est dispersé et difficile à prioriser. Ils passent des heures à trier manuellement pour comprendre ce que veulent vraiment leurs utilisateurs.",
    "solution": "Un outil qui centralise et analyse tous les feedbacks par IA : connexion aux sources (email, chat, reviews, réseaux sociaux), catégorisation automatique par thème, détection des demandes récurrentes, scoring de priorité basé sur l'impact business. Cible : fondateurs et product managers. Pricing suggéré : 39€/mois.",
    "competitors": "Canny, ProductBoard existent mais sont chers et sans vraie analyse IA.",
    "weekTrend": "stable"
  },
  {
    "id": 17,
    "name": "Outil de migration no-code vers code",
    "category": "tech",
    "score": 58,
    "scores": {
      "demande": 14,
      "croissance": 15,
      "concurrence": 12,
      "monetisation": 9,
      "faisabilite": 8
    },
    "trend": "+60%",
    "market": "€280M",
    "type": "SaaS / Service",
    "mentions": 210,
    "sources": "Reddit, Indie Hackers",
    "problem": "Beaucoup de startups démarrent sur Bubble, Webflow ou Airtable puis atteignent les limites du no-code. La migration vers du vrai code est un projet complexe et coûteux, souvent mal estimé.",
    "solution": "Un service qui analyse l'app no-code existante et génère une base de code propre (React/Node) avec l'IA, prête à être reprise par un développeur. Audit automatique, estimation du coût de migration, génération du code de base. Cible : startups post no-code. Pricing suggéré : 2000-5000€ ou SaaS 99€/mois.",
    "competitors": "Marché quasi inexistant. Quelques agences le font manuellement.",
    "weekTrend": "stable"
  },
  {
    "id": 18,
    "name": "API de vérification de conformité RGPD",
    "category": "tech",
    "score": 65,
    "scores": {
      "demande": 16,
      "croissance": 15,
      "concurrence": 13,
      "monetisation": 11,
      "faisabilite": 10
    },
    "trend": "+68%",
    "market": "€1.1B",
    "type": "API / SaaS",
    "mentions": 310,
    "sources": "Reddit, HackerNews, LinkedIn",
    "problem": "Les développeurs et petites boîtes ne savent pas si leur produit est conforme au RGPD. Les audits juridiques coûtent cher. Les plugins de cookies ne suffisent pas — il faut aussi vérifier le stockage des données, les sous-traitants, les durées de conservation.",
    "solution": "Une API qui scanne un site ou une app et génère un rapport de conformité RGPD automatique : cookies, trackers, politique de confidentialité, flux de données, sous-traitants détectés. Rapport PDF + plan d'action. Cible : développeurs, startups, PME. Pricing suggéré : 29€/mois.",
    "competitors": "Cookiebot, OneTrust sont orientés grands groupes et très chers.",
    "weekTrend": "stable"
  },
  {
    "id": 19,
    "name": "Outil d'audit UX automatisé par IA",
    "category": "tech",
    "score": 72,
    "scores": {
      "demande": 18,
      "croissance": 17,
      "concurrence": 15,
      "monetisation": 11,
      "faisabilite": 11
    },
    "trend": "+98%",
    "market": "€580M",
    "type": "SaaS",
    "mentions": 370,
    "sources": "Product Hunt, Reddit, Twitter/X",
    "problem": "La plupart des sites ont des problèmes UX qui font fuir les utilisateurs mais les fondateurs ne les voient pas. Un audit UX professionnel coûte 2000-5000€. Les outils d'analytics montrent le quoi mais pas le pourquoi.",
    "solution": "Un outil qui analyse automatiquement l'UX d'un site : screenshot de chaque page, analyse IA des patterns problématiques, score UX par page, recommandations priorisées avec maquettes de correction. Cible : fondateurs, product managers, freelances. Pricing suggéré : 39€/mois.",
    "competitors": "Hotjar et Crazy Egg montrent les données. L'analyse IA avec recommandations est le différenciateur.",
    "weekTrend": "stable"
  },
  {
    "id": 20,
    "name": "Outil de veille réglementaire IA pour PME",
    "category": "tech",
    "score": 63,
    "scores": {
      "demande": 16,
      "croissance": 15,
      "concurrence": 13,
      "monetisation": 10,
      "faisabilite": 9
    },
    "trend": "+62%",
    "market": "€520M",
    "type": "SaaS",
    "mentions": 270,
    "sources": "LinkedIn, Reddit, Google Trends",
    "problem": "Les PME sont soumises à de plus en plus de réglementations (RGPD, facturation électronique, RSE, accessibilité...) et n'ont pas de juriste interne. Elles découvrent les nouvelles obligations au dernier moment, parfois par une amende.",
    "solution": "Un outil de veille réglementaire personnalisé : l'entreprise renseigne son profil, l'IA surveille les évolutions légales pertinentes, envoie des alertes en langage clair avec les actions à mener et les échéances. Cible : dirigeants et DAF de PME. Pricing suggéré : 49€/mois.",
    "competitors": "Les cabinets d'avocats font ça manuellement. Pas d'outil IA accessible pour les PME.",
    "weekTrend": "stable"
  },
  {
    "id": 21,
    "name": "App de suivi nutritionnel IA personnalisé",
    "category": "sante",
    "score": 76,
    "scores": {
      "demande": 20,
      "croissance": 18,
      "concurrence": 14,
      "monetisation": 12,
      "faisabilite": 12
    },
    "trend": "+110%",
    "market": "€2.4B",
    "type": "App",
    "mentions": 580,
    "sources": "Reddit, Twitter/X, Google Trends",
    "problem": "Les apps de nutrition existantes demandent de scanner chaque aliment manuellement. C'est fastidieux, les gens abandonnent après 2 semaines. Les recommandations sont génériques et ne tiennent pas compte des pathologies ou préférences culturelles.",
    "solution": "Une app qui utilise la photo pour identifier les repas, calcule les macros automatiquement, et génère des recommandations personnalisées basées sur les objectifs santé, allergies, préférences culturelles. Coaching IA adaptatif. Cible : personnes soucieuses de leur alimentation. Pricing suggéré : 9.99€/mois.",
    "competitors": "MyFitnessPal domine mais UX datée. L'angle IA + photo + personnalisation est sous-exploité.",
    "weekTrend": "stable"
  },
  {
    "id": 22,
    "name": "Plateforme de coordination soins à domicile",
    "category": "sante",
    "score": 70,
    "scores": {
      "demande": 18,
      "croissance": 17,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 10
    },
    "trend": "+90%",
    "market": "€3.8B",
    "type": "SaaS",
    "mentions": 420,
    "sources": "Forums santé, LinkedIn, Google Trends",
    "problem": "Les soins à domicile impliquent infirmiers, aides-soignants, médecins, kinés — tous avec leurs propres plannings. La coordination est faite par téléphone et cahier de liaison papier. Les familles n'ont aucune visibilité.",
    "solution": "Une plateforme de coordination : planning partagé, cahier de liaison numérique, alertes médicamenteuses, accès famille en lecture seule, rapport automatique pour le médecin traitant. Cible : SSIAD, services de soins à domicile. Pricing suggéré : 49€/mois par structure.",
    "competitors": "Marché très fragmenté, outils vieillissants. Opportunité forte.",
    "weekTrend": "stable"
  },
  {
    "id": 23,
    "name": "IA de pré-triage pour urgences",
    "category": "sante",
    "score": 64,
    "scores": {
      "demande": 17,
      "croissance": 16,
      "concurrence": 12,
      "monetisation": 10,
      "faisabilite": 9
    },
    "trend": "+75%",
    "market": "€1.5B",
    "type": "SaaS B2B",
    "mentions": 290,
    "sources": "PubMed, Twitter/X, Reddit",
    "problem": "Les urgences hospitalières sont saturées. 40% des passages ne relèvent pas de l'urgence réelle. Les patients attendent des heures sans savoir s'ils devraient plutôt consulter leur médecin.",
    "solution": "Un chatbot IA de pré-triage : le patient décrit ses symptômes, l'IA évalue le niveau d'urgence et oriente (urgences, médecin de garde, téléconsultation, pharmacie). Cible : hôpitaux, ARS, mutuelles. Pricing suggéré : licence B2B 500€/mois.",
    "competitors": "Quelques initiatives publiques mais pas de solution IA clé en main.",
    "weekTrend": "stable"
  },
  {
    "id": 24,
    "name": "Marketplace kinés / ostéos à domicile",
    "category": "sante",
    "score": 61,
    "scores": {
      "demande": 16,
      "croissance": 15,
      "concurrence": 12,
      "monetisation": 10,
      "faisabilite": 8
    },
    "trend": "+55%",
    "market": "€920M",
    "type": "Marketplace",
    "mentions": 240,
    "sources": "Google Trends, Forums santé",
    "problem": "Trouver un kiné ou un ostéo qui se déplace à domicile est compliqué. Les plateformes comme Doctolib ne filtrent pas facilement par déplacement. Les personnes âgées ou à mobilité réduite sont les premières touchées.",
    "solution": "Une marketplace spécialisée : recherche par localisation, profils vérifiés, réservation en ligne, paiement sécurisé, avis patients. Côté praticien : gestion du planning et zone de déplacement. Cible : patients à domicile + praticiens. Commission : 10-15% par séance.",
    "competitors": "Doctolib domine le RDV médical mais ne gère pas le déplacement à domicile.",
    "weekTrend": "stable"
  },
  {
    "id": 25,
    "name": "App de gestion de stock pour pharmacies",
    "category": "sante",
    "score": 60,
    "scores": {
      "demande": 15,
      "croissance": 14,
      "concurrence": 13,
      "monetisation": 10,
      "faisabilite": 8
    },
    "trend": "+50%",
    "market": "€640M",
    "type": "SaaS",
    "mentions": 220,
    "sources": "Forums pharma, LinkedIn",
    "problem": "Les pharmacies gèrent leur stock avec les logiciels des grossistes, qui ne communiquent pas entre eux. Les ruptures sont fréquentes, les péremptions génèrent des pertes, et la gestion multi-fournisseurs est chronophage.",
    "solution": "Un outil de gestion de stock intelligent : prédiction IA des besoins, alerte péremption, comparaison automatique des prix entre grossistes, commande optimisée multi-fournisseurs. Cible : pharmacies indépendantes. Pricing suggéré : 89€/mois.",
    "competitors": "Les logiciels de gestion officinale sont limités en IA prédictive.",
    "weekTrend": "stable"
  },
  {
    "id": 26,
    "name": "Assistant IA pour rédaction médicale",
    "category": "sante",
    "score": 67,
    "scores": {
      "demande": 17,
      "croissance": 16,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 9
    },
    "trend": "+80%",
    "market": "€740M",
    "type": "SaaS",
    "mentions": 300,
    "sources": "PubMed, LinkedIn, Twitter/X",
    "problem": "Les médecins passent 2-3 heures par jour sur de la paperasse : comptes-rendus, courriers aux confrères, certificats. La dictée vocale ne structure pas le contenu médical. Le burnout médical est en partie lié à cette charge administrative.",
    "solution": "Un assistant IA spécialisé : dictée vocale avec structuration automatique, génération de courriers aux spécialistes, templates par spécialité, intégration aux logiciels métier. Cible : médecins libéraux. Pricing suggéré : 59€/mois.",
    "competitors": "Quelques acteurs émergents (Nabla) mais le marché est encore très ouvert.",
    "weekTrend": "stable"
  },
  {
    "id": 27,
    "name": "Plateforme de second avis médical IA",
    "category": "sante",
    "score": 55,
    "scores": {
      "demande": 14,
      "croissance": 14,
      "concurrence": 11,
      "monetisation": 9,
      "faisabilite": 7
    },
    "trend": "+42%",
    "market": "€580M",
    "type": "Marketplace / App",
    "mentions": 190,
    "sources": "Reddit, Google Trends",
    "problem": "Quand un patient reçoit un diagnostic grave ou incertain, obtenir un second avis médical est long (6-12 semaines), coûteux et compliqué.",
    "solution": "Une plateforme de second avis : le patient upload son dossier médical, l'IA pré-analyse et oriente vers le bon spécialiste, le médecin rend son avis sous 48-72h. Cible : patients, mutuelles. Pricing suggéré : 150-300€ par avis.",
    "competitors": "Deuxième Avis existe mais le marché reste embryonnaire en France.",
    "weekTrend": "stable"
  },
  {
    "id": 28,
    "name": "Outil de scoring locataire pour propriétaires",
    "category": "immobilier",
    "score": 78,
    "scores": {
      "demande": 19,
      "croissance": 19,
      "concurrence": 16,
      "monetisation": 12,
      "faisabilite": 12
    },
    "trend": "+125%",
    "market": "€780M",
    "type": "SaaS",
    "mentions": 510,
    "sources": "Reddit, Forums immo, Google Trends",
    "problem": "Les propriétaires reçoivent des dizaines de dossiers locataires et doivent les trier manuellement. Vérifier la solvabilité, l'authenticité des documents, comparer les profils — tout est chronophage.",
    "solution": "Un outil de scoring automatique : upload du dossier, vérification IA des documents, score de solvabilité, comparaison entre candidats, alertes fraude. Cible : propriétaires bailleurs et agences. Pricing suggéré : 5€ par dossier ou 29€/mois illimité.",
    "competitors": "Dossierfacile.fr existe mais ne fait pas de scoring ni de détection de fraude.",
    "weekTrend": "up"
  },
  {
    "id": 29,
    "name": "Simulateur investissement locatif IA",
    "category": "immobilier",
    "score": 72,
    "scores": {
      "demande": 18,
      "croissance": 17,
      "concurrence": 14,
      "monetisation": 12,
      "faisabilite": 11
    },
    "trend": "+95%",
    "market": "€1.4B",
    "type": "SaaS / App",
    "mentions": 460,
    "sources": "Reddit, YouTube, Google Trends",
    "problem": "Les investisseurs immobiliers débutants ne savent pas évaluer la rentabilité réelle d'un bien.",
    "solution": "Un simulateur avancé : estimation du rendement net-net, simulation fiscale (LMNP, Pinel, SCI), projection sur 10-20 ans. Cible : investisseurs particuliers. Pricing suggéré : freemium, 14.99€/mois premium.",
    "competitors": "Quelques simulateurs basiques en ligne mais aucun avec IA et données marché intégrées.",
    "weekTrend": "stable"
  },
  {
    "id": 30,
    "name": "Outil de visite virtuelle IA pour agences",
    "category": "immobilier",
    "score": 66,
    "scores": {
      "demande": 17,
      "croissance": 16,
      "concurrence": 13,
      "monetisation": 11,
      "faisabilite": 9
    },
    "trend": "+80%",
    "market": "€620M",
    "type": "SaaS",
    "mentions": 350,
    "sources": "Product Hunt, Google Trends, Twitter/X",
    "problem": "Créer des visites virtuelles coûte cher (photographe + Matterport). Les petites agences n'ont pas le budget.",
    "solution": "Un outil qui transforme de simples photos smartphone en visite virtuelle 3D grâce à l'IA. Cible : agences et mandataires. Pricing suggéré : 39€/mois.",
    "competitors": "Matterport domine le haut de gamme. Très peu d'offre accessible smartphone-only avec IA.",
    "weekTrend": "stable"
  },
  {
    "id": 31,
    "name": "Plateforme de coliving intelligent",
    "category": "immobilier",
    "score": 59,
    "scores": {
      "demande": 15,
      "croissance": 14,
      "concurrence": 12,
      "monetisation": 10,
      "faisabilite": 8
    },
    "trend": "+65%",
    "market": "€480M",
    "type": "Marketplace",
    "mentions": 280,
    "sources": "Reddit, Facebook Groups, Twitter/X",
    "problem": "Trouver des colocataires compatibles est un cauchemar. Les plateformes actuelles sont de simples petites annonces sans matching.",
    "solution": "Une plateforme de matching par IA : profil détaillé, algorithme de compatibilité. Cible : étudiants et jeunes actifs. Commission : 1 mois de loyer.",
    "competitors": "La Carte des Colocs est le leader mais sans matching intelligent.",
    "weekTrend": "stable"
  },
  {
    "id": 32,
    "name": "Outil de gestion de copropriété simplifié",
    "category": "immobilier",
    "score": 55,
    "scores": {
      "demande": 14,
      "croissance": 13,
      "concurrence": 11,
      "monetisation": 9,
      "faisabilite": 8
    },
    "trend": "+45%",
    "market": "€890M",
    "type": "SaaS",
    "mentions": 190,
    "sources": "Forums immo, Google Trends",
    "problem": "Les petites copropriétés ne trouvent pas de syndic professionnel ou paient trop cher.",
    "solution": "Un outil de syndic assistant : gestion des charges, convocation d'AG, votes en ligne. Cible : syndics bénévoles, petites copropriétés. Pricing suggéré : 9€/mois par copropriété.",
    "competitors": "Matera et Cotoit visent les copros moyennes à grandes.",
    "weekTrend": "stable"
  },
  {
    "id": 33,
    "name": "Outil de rédaction d'annonces immo IA",
    "category": "immobilier",
    "score": 70,
    "scores": {
      "demande": 17,
      "croissance": 17,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 11
    },
    "trend": "+90%",
    "market": "€320M",
    "type": "SaaS",
    "mentions": 350,
    "sources": "Twitter/X, Forums immo, Google Trends",
    "problem": "Les agents rédigent des dizaines d'annonces par mois avec les mêmes formules creuses.",
    "solution": "Un outil qui génère des annonces uniques et vendeuses. Cible : agents et mandataires. Pricing suggéré : 25€/mois.",
    "competitors": "Rien de spécialisé immobilier avec les bonnes données métier.",
    "weekTrend": "stable"
  },
  {
    "id": 34,
    "name": "SaaS gestion de parc immobilier pour SCI",
    "category": "immobilier",
    "score": 58,
    "scores": {
      "demande": 15,
      "croissance": 14,
      "concurrence": 12,
      "monetisation": 9,
      "faisabilite": 8
    },
    "trend": "+52%",
    "market": "€340M",
    "type": "SaaS",
    "mentions": 230,
    "sources": "Forums immo, Reddit",
    "problem": "Les SCI familiales n'ont aucun outil adapté.",
    "solution": "Un outil dédié SCI : comptabilité simplifiée, suivi de rentabilité par bien. Cible : gérants de SCI. Pricing suggéré : 19€/mois par SCI.",
    "competitors": "Les logiciels comptables classiques ne gèrent pas les spécificités SCI.",
    "weekTrend": "up"
  },
  {
    "id": 35,
    "name": "App de suivi de chantier par photo IA",
    "category": "btp",
    "score": 80,
    "scores": {
      "demande": 20,
      "croissance": 20,
      "concurrence": 16,
      "monetisation": 12,
      "faisabilite": 12
    },
    "trend": "+150%",
    "market": "€1.8B",
    "type": "App",
    "mentions": 680,
    "sources": "Forums BTP, Reddit, Google Trends",
    "problem": "Le suivi de chantier se fait par WhatsApp et photos en vrac.",
    "solution": "Une app mobile ultra simple : photo → l'IA catégorise, géolocalise et horodate. Cible : artisans et chefs de chantier TPE. Pricing suggéré : 19€/mois.",
    "competitors": "Finalcad et BatiScript visent les grands groupes. Quasi rien pour les TPE.",
    "weekTrend": "stable"
  },
  {
    "id": 36,
    "name": "Marketplace matériaux BTP entre pros",
    "category": "btp",
    "score": 69,
    "scores": {
      "demande": 17,
      "croissance": 17,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 10
    },
    "trend": "+80%",
    "market": "€2.1B",
    "type": "Marketplace",
    "mentions": 390,
    "sources": "Forums BTP, Reddit",
    "problem": "Les artisans achètent chez 2-3 fournisseurs habituels sans comparer.",
    "solution": "Une marketplace B2B : comparateur de prix fournisseurs locaux, revente de surplus entre artisans. Commission : 5-8% par transaction.",
    "competitors": "StockPro fait les surplus mais pas de plateforme complète prix + surplus.",
    "weekTrend": "stable"
  },
  {
    "id": 37,
    "name": "Outil de conformité RE2020 automatisé",
    "category": "btp",
    "score": 63,
    "scores": {
      "demande": 16,
      "croissance": 16,
      "concurrence": 13,
      "monetisation": 10,
      "faisabilite": 8
    },
    "trend": "+70%",
    "market": "€560M",
    "type": "SaaS",
    "mentions": 310,
    "sources": "Forums BTP, LinkedIn, Google Trends",
    "problem": "La RE2020 impose de nouvelles normes thermiques et carbone.",
    "solution": "Un outil simplifié : caractéristiques du projet → calcul conformité. Cible : constructeurs, architectes. Pricing suggéré : 79€/mois.",
    "competitors": "Pleiades, ClimaWin sont complexes et chers. Pas d'offre simplifiée IA.",
    "weekTrend": "stable"
  },
  {
    "id": 38,
    "name": "Plateforme mise en relation chantier/artisan",
    "category": "btp",
    "score": 56,
    "scores": {
      "demande": 15,
      "croissance": 13,
      "concurrence": 11,
      "monetisation": 9,
      "faisabilite": 8
    },
    "trend": "+45%",
    "market": "€1.3B",
    "type": "Marketplace",
    "mentions": 260,
    "sources": "Google Trends, Forums BTP",
    "problem": "Les particuliers galèrent à trouver des artisans fiables.",
    "solution": "Une plateforme avec meilleur matching par IA. Commission : 15€ par mise en relation.",
    "competitors": "Marché concurrentiel mais la qualité du matching reste le point faible de tous.",
    "weekTrend": "stable"
  },
  {
    "id": 39,
    "name": "Logiciel planification de chantier IA",
    "category": "btp",
    "score": 52,
    "scores": {
      "demande": 13,
      "croissance": 13,
      "concurrence": 11,
      "monetisation": 8,
      "faisabilite": 7
    },
    "trend": "+40%",
    "market": "€720M",
    "type": "SaaS",
    "mentions": 180,
    "sources": "Forums BTP, LinkedIn",
    "problem": "La planification pour les petites entreprises se fait sur Excel.",
    "solution": "Un planning visuel intelligent : Gantt simplifié, gestion des dépendances. Cible : chefs de chantier TPE/PME. Pricing suggéré : 39€/mois.",
    "competitors": "MS Project est surdimensionné. Quelques apps existent mais sans IA.",
    "weekTrend": "stable"
  },
  {
    "id": 40,
    "name": "Plateforme formation IA pour artisans",
    "category": "btp",
    "score": 48,
    "scores": {
      "demande": 12,
      "croissance": 12,
      "concurrence": 10,
      "monetisation": 8,
      "faisabilite": 6
    },
    "trend": "+35%",
    "market": "€380M",
    "type": "Plateforme",
    "mentions": 150,
    "sources": "Forums BTP, YouTube",
    "problem": "Les artisans doivent se former continuellement mais les formations classiques sont chères.",
    "solution": "Micro-formations vidéo de 10-15 minutes, certifiantes. Cible : artisans en activité. Pricing suggéré : 19€/mois.",
    "competitors": "Peu de formation en ligne spécifique BTP.",
    "weekTrend": "stable"
  },
  {
    "id": 41,
    "name": "Outil calcul bilan carbone chantier",
    "category": "btp",
    "score": 51,
    "scores": {
      "demande": 13,
      "croissance": 12,
      "concurrence": 11,
      "monetisation": 8,
      "faisabilite": 7
    },
    "trend": "+38%",
    "market": "€290M",
    "type": "SaaS",
    "mentions": 170,
    "sources": "LinkedIn, Forums BTP",
    "problem": "La réglementation pousse au calcul de l'empreinte carbone mais les outils sont complexes.",
    "solution": "Un outil simplifié : matériaux et quantités → empreinte calculée. Cible : PME BTP. Pricing suggéré : 49€/mois.",
    "competitors": "Elodie, Vizcab sont experts. Rien de simplifié pour TPE/PME.",
    "weekTrend": "up"
  },
  {
    "id": 42,
    "name": "Générateur de landing pages IA",
    "category": "marketing",
    "score": 80,
    "scores": {
      "demande": 20,
      "croissance": 19,
      "concurrence": 16,
      "monetisation": 13,
      "faisabilite": 12
    },
    "trend": "+140%",
    "market": "€1.6B",
    "type": "SaaS",
    "mentions": 720,
    "sources": "Product Hunt, Reddit, Twitter/X",
    "problem": "Créer une landing page qui convertit demande des compétences en copywriting, design et technique.",
    "solution": "L'utilisateur décrit son offre → l'IA génère une landing page complète. Cible : freelances, solopreneurs, PME. Pricing suggéré : 19€/mois.",
    "competitors": "Carrd, Unbounce existent mais aucun ne fait la stratégie + le copy par IA.",
    "weekTrend": "stable"
  },
  {
    "id": 43,
    "name": "Outil d'analyse de concurrents par IA",
    "category": "marketing",
    "score": 76,
    "scores": {
      "demande": 19,
      "croissance": 18,
      "concurrence": 15,
      "monetisation": 12,
      "faisabilite": 12
    },
    "trend": "+105%",
    "market": "€920M",
    "type": "SaaS",
    "mentions": 480,
    "sources": "Reddit, Indie Hackers, Product Hunt",
    "problem": "Surveiller ses concurrents demande de checker manuellement leurs sites, réseaux sociaux, prix.",
    "solution": "Un radar concurrentiel IA : suivi automatique des changements, analyse des stratégies. Cible : fondateurs SaaS. Pricing suggéré : 39€/mois.",
    "competitors": "Crayon, Kompyte sont orientés enterprise à +200€/mois.",
    "weekTrend": "stable"
  },
  {
    "id": 44,
    "name": "Plateforme de création de newsletters IA",
    "category": "marketing",
    "score": 73,
    "scores": {
      "demande": 18,
      "croissance": 18,
      "concurrence": 14,
      "monetisation": 12,
      "faisabilite": 11
    },
    "trend": "+115%",
    "market": "€780M",
    "type": "SaaS",
    "mentions": 520,
    "sources": "Twitter/X, Product Hunt, Reddit",
    "problem": "Lancer et maintenir une newsletter demande énormément de travail.",
    "solution": "Suggestion de sujets tendance, rédaction assistée avec le ton de l'auteur. Cible : créateurs, solopreneurs. Pricing suggéré : 15€/mois.",
    "competitors": "Substack et Beehiiv dominent la distribution. L'angle création IA est le différenciateur.",
    "weekTrend": "stable"
  },
  {
    "id": 45,
    "name": "Outil de repurposing de contenu IA",
    "category": "marketing",
    "score": 71,
    "scores": {
      "demande": 18,
      "croissance": 17,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 11
    },
    "trend": "+100%",
    "market": "€620M",
    "type": "SaaS",
    "mentions": 440,
    "sources": "Twitter/X, Reddit, YouTube",
    "problem": "Les créateurs passent des heures sur un contenu long puis n'ont plus le temps de le décliner.",
    "solution": "Un outil qui prend un contenu source et génère des déclinaisons pour chaque plateforme. Cible : créateurs, marketeurs. Pricing suggéré : 25€/mois.",
    "competitors": "Repurpose.io fait de la vidéo. Aucun ne fait tout avec IA.",
    "weekTrend": "stable"
  },
  {
    "id": 46,
    "name": "Outil de social proof automatisé",
    "category": "marketing",
    "score": 67,
    "scores": {
      "demande": 16,
      "croissance": 16,
      "concurrence": 14,
      "monetisation": 11,
      "faisabilite": 10
    },
    "trend": "+75%",
    "market": "€340M",
    "type": "SaaS",
    "mentions": 310,
    "sources": "Indie Hackers, Product Hunt, Twitter/X",
    "problem": "Collecter et afficher des témoignages clients est manuel.",
    "solution": "Collecte automatisée, formulaire vidéo simplifié. Cible : SaaS, freelances, e-commerce. Pricing suggéré : 25€/mois.",
    "competitors": "Senja, Testimonial.to émergent mais marché fragmenté.",
    "weekTrend": "stable"
  },
  {
    "id": 47,
    "name": "Générateur de stratégie SEO par IA",
    "category": "marketing",
    "score": 69,
    "scores": {
      "demande": 17,
      "croissance": 17,
      "concurrence": 13,
      "monetisation": 11,
      "faisabilite": 11
    },
    "trend": "+88%",
    "market": "€1.2B",
    "type": "SaaS",
    "mentions": 380,
    "sources": "Reddit, Twitter/X, Product Hunt",
    "problem": "Les freelances et PME savent que le SEO est important mais ne savent pas par où commencer.",
    "solution": "Analyse du site → opportunités de mots-clés → plan de contenu SEO priorisé. Cible : freelances, PME. Pricing suggéré : 29€/mois.",
    "competitors": "SEMrush et Ahrefs dominent les données. L'angle stratégie actionnable IA est libre.",
    "weekTrend": "stable"
  },
  {
    "id": 48,
    "name": "CRM gestion d'influenceurs pour PME",
    "category": "marketing",
    "score": 62,
    "scores": {
      "demande": 15,
      "croissance": 15,
      "concurrence": 13,
      "monetisation": 10,
      "faisabilite": 9
    },
    "trend": "+65%",
    "market": "€480M",
    "type": "SaaS",
    "mentions": 280,
    "sources": "Twitter/X, LinkedIn, Reddit",
    "problem": "Les PME veulent travailler avec des micro-influenceurs mais ne savent pas comment.",
    "solution": "Un CRM simplifié : recherche d'influenceurs par niche et localisation. Cible : PME et e-commerçants. Pricing suggéré : 39€/mois.",
    "competitors": "Kolsquare, Upfluence visent les grands comptes.",
    "weekTrend": "stable"
  },
  {
    "id": 49,
    "name": "Outil gestion des avis Google pour PME",
    "category": "marketing",
    "score": 66,
    "scores": {
      "demande": 17,
      "croissance": 15,
      "concurrence": 13,
      "monetisation": 11,
      "faisabilite": 10
    },
    "trend": "+72%",
    "market": "€460M",
    "type": "SaaS",
    "mentions": 290,
    "sources": "Google Trends, Reddit, Forums PME",
    "problem": "Les avis Google sont le premier critère de choix pour les commerces locaux.",
    "solution": "Demande automatisée d'avis après chaque prestation, réponses générées par IA. Cible : commerces, restaurants. Pricing suggéré : 29€/mois.",
    "competitors": "Partoo, Localranker existent mais marché fragmenté.",
    "weekTrend": "stable"
  },
  {
    "id": 50,
    "name": "Bot LinkedIn lead gen pour agences",
    "category": "marketing",
    "score": 64,
    "scores": {
      "demande": 16,
      "croissance": 15,
      "concurrence": 13,
      "monetisation": 11,
      "faisabilite": 9
    },
    "trend": "+70%",
    "market": "€560M",
    "type": "SaaS",
    "mentions": 340,
    "sources": "Reddit, Twitter/X, LinkedIn",
    "problem": "Les agences prospectent sur LinkedIn manuellement.",
    "solution": "Identification des prospects par IA, messages hyper-personnalisés. Cible : agences marketing. Pricing suggéré : 59€/mois.",
    "competitors": "Waalaxy, Phantombuster existent. La personnalisation IA profonde est le différenciateur.",
    "weekTrend": "stable"
  },
  {
    "id": 51,
    "name": "Plateforme micro-learning marketing",
    "category": "marketing",
    "score": 54,
    "scores": {
      "demande": 14,
      "croissance": 13,
      "concurrence": 11,
      "monetisation": 9,
      "faisabilite": 7
    },
    "trend": "+48%",
    "market": "€420M",
    "type": "Plateforme",
    "mentions": 210,
    "sources": "Reddit, Twitter/X",
    "problem": "Les freelances doivent constamment apprendre de nouvelles compétences marketing.",
    "solution": "Micro-formations de 10 minutes. Cible : freelances marketing. Pricing suggéré : 15€/mois.",
    "competitors": "Udemy et Coursera sont généralistes. Le micro-learning marketing spécialisé est libre.",
    "weekTrend": "stable"
  },
  {
    "id": 52,
    "name": "Outil de diagnostic et maintenance prédictive IA pour équipements médicaux",
    "category": "sante",
    "score": 81,
    "scores": {
      "demande": 22,
      "croissance": 21,
      "concurrence": 17,
      "monetisation": 12,
      "faisabilite": 9
    },
    "trend": "+145%",
    "market": "€2.8B",
    "type": "SaaS",
    "mentions": 680,
    "sources": "LinkedIn Healthcare, MedTech Forums, Google Trends",
    "problem": "Les hôpitaux et cliniques perdent des millions d'euros chaque année à cause de pannes d'équipements médicaux critiques imprévisibles. Les coûts de maintenance curative sont 3x plus élevés que la maintenance préventive, et les arrêts d'équipements impactent directement la qualité des soins. Les équipes techniques manquent de visibilité sur l'état réel des machines et planifient mal leur maintenance.",
    "solution": "Plateforme SaaS qui connecte les équipements médicaux via IoT et utilise l'IA pour prédire les pannes avant qu'elles surviennent. Cible les établissements de santé de 50+ lits avec un pricing de 200-500€/mois par équipement connecté. L'outil analyse les données de fonctionnement, alerte en cas d'anomalie et optimise la planification de maintenance. ROI démontrable de 30-40% sur les coûts de maintenance et réduction de 60% des pannes imprévues.",
    "competitors": "Marché encore émergent avec quelques acteurs comme Philips HealthSuite mais principalement sur leurs propres équipements. Peu de solutions cross-constructeurs abordables pour les établissements moyens.",
    "weekTrend": "new"
  },
  {
    "id": 53,
    "name": "Plateforme de tokenisation et fractionnement d'investissements immobiliers",
    "category": "immobilier",
    "score": 76,
    "scores": {
      "demande": 19,
      "croissance": 20,
      "concurrence": 15,
      "monetisation": 13,
      "faisabilite": 9
    },
    "trend": "+180%",
    "market": "€850M",
    "type": "FinTech",
    "mentions": 520,
    "sources": "CoinTelegraph, Real Estate News, Twitter/X",
    "problem": "L'investissement immobilier reste inaccessible pour les petits épargnants qui ne peuvent pas débourser 100k€+ pour un bien. Les SCPI ont des frais élevés (3-5%) et peu de liquidité. Les jeunes investisseurs cherchent des alternatives digitales pour accéder à l'immobilier avec des tickets d'entrée réduits et plus de transparence sur leurs investissements.",
    "solution": "Plateforme qui tokénise des biens immobiliers sélectionnés permettant d'acheter des parts dès 100€. Cible les 25-45 ans avec revenus moyens-élevés. Commission de 1,5% sur les transactions plus frais de gestion annuels de 0,8%. La blockchain assure la transparence des propriétés, les smart contracts automatisent la redistribution des loyers, et un marché secondaire permet la revente des tokens. KYC intégré et conformité réglementaire française.",
    "competitors": "RealT en France, Fundrise aux US, mais marché français encore peu mature avec des barrières réglementaires qui se lèvent progressivement. Avantage premier entrant.",
    "weekTrend": "new"
  },
  {
    "id": 54,
    "name": "Assistant IA conversationnel pour la formation et reskilling des employés",
    "category": "tech",
    "score": 83,
    "scores": {
      "demande": 23,
      "croissance": 22,
      "concurrence": 16,
      "monetisation": 13,
      "faisabilite": 9
    },
    "trend": "+165%",
    "market": "€4.2B",
    "type": "SaaS",
    "mentions": 750,
    "sources": "HR Tech News, LinkedIn Learning, Stack Overflow",
    "problem": "Les entreprises peinent à former leurs employés aux nouvelles technologies et compétences digitales. Les formations traditionnelles sont coûteuses, peu engageantes et mal adaptées aux besoins individuels. Avec l'évolution rapide des métiers, 40% des compétences deviennent obsolètes en 5 ans. Les RH cherchent des solutions personnalisées et scalables pour le upskilling continu de leurs équipes.",
    "solution": "Chatbot IA intégré aux outils de l'entreprise qui crée des parcours de formation personnalisés et accompagne l'apprentissage en temps réel. Cible les entreprises 100+ employés à 15-25€/employé/mois. L'IA analyse les lacunes de compétences, propose du contenu adapté au poste et niveau, répond aux questions pendant l'apprentissage et mesure la progression. Intégration Slack/Teams et analytics pour les managers RH.",
    "competitors": "Coursera for Business, LinkedIn Learning dominent mais avec approche catalogue classique. Peu d'acteurs avec IA conversationnelle vraiment personnalisée et intégrée au workflow.",
    "weekTrend": "new"
  },
  {
    "id": 55,
    "name": "Repurposing de contenu IA",
    "category": "marketing",
    "score": 88,
    "scores": {
      "demande": 23,
      "croissance": 22,
      "concurrence": 16,
      "monetisation": 14,
      "faisabilite": 13
    },
    "trend": "+260%",
    "market": "€2.4B",
    "type": "SaaS",
    "mentions": 1420,
    "sources": "Reddit, Twitter/X, Product Hunt, Google Trends",
    "problem": "Un consultant enregistre 1 podcast d'1 heure avec 10 idées géniales dedans. Transformer ce podcast en posts LinkedIn, tweets, newsletter et Reels lui prend 2 jours. Du coup il ne le fait pas, et son podcast meurt sur Spotify avec 200 écoutes. Les créateurs de contenu perdent un temps colossal à décliner manuellement leur contenu sur chaque plateforme, alors que la matière première existe déjà.",
    "solution": "Un SaaS où tu uploades ton podcast, ta vidéo YouTube ou ton article. L'IA écoute tout, repère les meilleurs moments, et génère automatiquement 10 posts LinkedIn prêts à publier, 20 tweets, 1 newsletter, et 5 idées de Reels/Shorts. Tu copies-colles ou tu planifies directement. 1 heure de contenu = 1 mois de présence sur les réseaux. Pour un consultant qui facture 1500€/jour, gagner 2 jours par mois = 3000€ économisés. Pricing : 49€/mois. Cible : consultants, coachs, freelances, créateurs de contenu.",
    "competitors": "Opus Clip fait du découpage vidéo, Castmagic transcrit les podcasts, mais aucun ne génère un kit complet multi-plateforme prêt à publier en un clic. Le marché est fragmenté avec des outils mono-format.",
    "weekTrend": "new"
  },
  {
    "id": 56,
    "name": "Kits marketing immobilier IA",
    "category": "immobilier",
    "score": 85,
    "scores": {
      "demande": 22,
      "croissance": 20,
      "concurrence": 17,
      "monetisation": 13,
      "faisabilite": 13
    },
    "trend": "+190%",
    "market": "€1.8B",
    "type": "SaaS",
    "mentions": 980,
    "sources": "Reddit, Forums Immobilier, Google Trends",
    "problem": "Un agent immobilier débutant signe son premier mandat. Il doit créer une annonce qui vend, retoucher les photos, faire une fiche PDF pro, un post Instagram, une vidéo de visite. Il ne sait pas faire. Il pond une annonce moche, et son bien reste 6 mois sans visite. Les 40 000 agents en France n'ont pas les moyens d'un graphiste interne, surtout les indépendants.",
    "solution": "L'agent rentre l'adresse et uploade ses photos brutes. L'IA génère automatiquement un texte d'annonce vendeur, des photos retouchées (luminosité, ciel bleu), une fiche PDF avec son logo, un post Instagram + Reel, et une description SEO pour SeLoger/LeBonCoin. En 5 minutes, il a un kit complet pro. Un agent gagne 3000-8000€ de commission par vente — s'il vend 1 bien de plus par mois grâce à un meilleur marketing, 39€/mois c'est ridicule. Cible : agents indépendants et petites agences.",
    "competitors": "Quelques outils de retouche photo immobilière (Nodalview, Homestaging3D) mais aucun ne propose un kit marketing complet avec texte + visuels + réseaux sociaux + SEO généré par IA en une seule plateforme.",
    "weekTrend": "new"
  }
];
